#!/bin/bash

#
# Copyright (C) 2020 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

#
# Find today's most blocked source hosts.
#

day=$1      # day of month with this format: "Feb 25"
lines=$2    # maximum number of entries to output

/usr/bin/grep "$day" /var/log/firewall.log | /usr/bin/grep blacklst | /usr/bin/grep -oE -e 'SRC=([0-9]{1,3}[\.]){3}[0-9]{1,3}' | /usr/bin/cut -d'=' -f2 | /usr/bin/sort | /usr/bin/uniq -c | /usr/bin/sort -rn | /usr/bin/head -n "$lines"
