#!/bin/bash

#
# Copyright (C) 2020 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

# get TYPE from event (ipsets or dnss)
TYPE=$1

# switch prop based on type
PROP=blacklist
case $TYPE in
    ipsets)
        PROP=blacklist
        ;;

    dnss)
        PROP=ftl
        ;;
esac

URL=$(/sbin/e-smith/config getprop $PROP Url)
SYSTEM_ID=$(/sbin/e-smith/config getprop subscription SystemId)
SYSTEM_SECRET=$(/sbin/e-smith/config getprop subscription Secret)
DEST_DIR=/usr/share/nethserver-blacklist/$TYPE
DEBUG=0

function exit_error {
    >&2 echo "[ERROR] $@"
    exit 1
}

function debug {
    if [ $DEBUG -eq 1 ]; then
        echo "[DEBUG] $@"
    fi
}


options=$(getopt -o d --long debug -- "$@")
[ $? -eq 0 ] || {
    >&2 echo "Incorrect options provided"
    exit 1
}
eval set -- "$options"
while true; do
    case "$1" in
    --debug|-d)
        DEBUG=1
        ;;
    --)
        shift
        break
        ;;
    esac
    shift
done


if [ -z "$URL" ]; then
    exit_error "Blacklist URL is not set"
fi

# Prepare work directory
mkdir -p $DEST_DIR

# Inject authentication into URL
proto="$(echo $URL | grep :// | sed -e's,^\(.*://\).*,\1,g')"
url="$(echo ${URL/$proto/})"
auth=""
if [[ ! -z "$SYSTEM_SECRET" && ! -z "$SYSTEM_ID" ]]; then
    auth="$SYSTEM_ID:$SYSTEM_SECRET@"
fi

# Set git output
quiet=""
if [ $DEBUG -eq  0 ]; then
    quiet=" --quiet "
fi

# Create repository clone
if [ ! -d "$DEST_DIR/.git" ]; then
    debug "Cloning repository"
    git clone --depth 1 $quiet $proto$auth$url $DEST_DIR
    if [ $? -gt 0 ]; then
        exit_error "Can't download blacklist repository"
    fi

    # do not leak secret
    chmod 600 "$DEST_DIR/.git/config"
else
    # Pull changes
    opts="--git-dir=$DEST_DIR/.git --work-tree=$DEST_DIR"
    debug "Pulling changes"

    git $opts fetch --all &>/dev/null
    if [ $? -gt 0 ]; then
        exit_error "Can't update blacklist repository: fetch failed"
    fi
    git $opts reset --hard origin/master &>/dev/null
    if [ $? -eq 0 ]; then
        debug_flag=""
        if [ $DEBUG -eq 1 ]; then
            debug_flag="-d"
        fi
        debug "Repository have been updated: reloading $TYPE"
        exec /usr/share/nethserver-blacklist/load-$TYPE --reload $debug_flag
    else
        debug "Can't update blacklist repository: hard reset failed"
    fi
fi
