#!/bin/bash

#
# Copyright (C) 2020 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

. /usr/libexec/nethserver/api/lib/helper_functions

# read json from stdin
data=$(cat /dev/stdin)

status=$(echo $data | jq -r '.status')
url=$(echo $data | jq -r '.Url')
whitelist=$(echo $data | jq -r '.Whitelist | join(",")')
categories=$(echo $data | jq -r '.Categories | join(",")')

current_url=$(/sbin/e-smith/config getprop blacklist Url)

if [ "$status" = "enabled" ]; then
    /sbin/e-smith/config setprop blacklist status "$status" Url "$url" Whitelist "$whitelist" Categories "$categories"

    if [ $? -gt 0 ]; then
        invalid_error
    fi
else
    /sbin/e-smith/config setprop blacklist status "$status"

    if [ $? -gt 0 ]; then
        invalid_error
    fi
fi

if [ "$current_url" != "$url" ]; then
    # clear active categories
    /sbin/e-smith/config setprop blacklist Categories ""
    if [ $? -gt 0 ]; then
        invalid_error
    fi

    # remove old blacklist categories
    /usr/bin/rm -rf /usr/share/nethserver-blacklist/ipsets
    if [ $? -gt 0 ]; then
        error "EventFailed" "See /var/log/messages"
    fi
fi

/sbin/e-smith/signal-event -j nethserver-blacklist-save
if [ $? -gt 0 ]; then
    error "EventFailed" "See /var/log/messages"
fi

success
