#!/bin/bash

#
# Copyright (C) 2020 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

#
# Download the blacklists for the first time
#
event=$1    # name of the event (not used)
type=$2     # blacklist type (ipsets or dnss)

if [[ "$type" == "ipsets" ]]; then
    status=$(/sbin/e-smith/config getprop blacklist status)
    ipsetUrl=$(/sbin/e-smith/config getprop blacklist Url)
    GeoipStatus=$(/sbin/e-smith/config getprop blacklist GeoipStatus)

    if [[ "$status" != "enabled" ]]; then
        exit 0
    fi

    if [[ "$ipsetUrl" != "" ]]; then
        /usr/share/nethserver-blacklist/download ipsets
    fi
    if [[ "$GeoipStatus" == "enabled" ]]; then
        /usr/share/nethserver-blacklist/download geoip
    fi


elif [[ "$type" == "dnss" ]]; then
    status=$(/sbin/e-smith/config getprop ftl status)

    if [[ "$status" == "enabled" ]]; then
        exec /usr/share/nethserver-blacklist/download dnss
    fi

else
    echo "Invalid blacklist type: $type"
    exit 1
fi
