#!/usr/bin/perl

#
# Copyright (C) 2020 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

require "/usr/libexec/nethserver/api/lib/helper_functions.pl";

use warnings;
use strict;
use String::ShellQuote qw( shell_quote );

my $TIMEOUT=300;
my $input = readInput();
my $cmd = $input->{'action'};
my $lines = $input->{'lines'} || '50';
my $filter = $input->{'filter'} || '';

sub dump_logs
{
    my $lines = shift;
    my $follow = shift;
    my $cmd = '';
    my $watchdog = '';

    if ($follow) {
        $cmd = "/usr/bin/tail -f /var/log/firewall.log | /usr/bin/grep --line-buffered blacklst";

        # Make sure process is killed after the timeout
        $watchdog= "timeout --foreground -k ".($TIMEOUT+5)." $TIMEOUT ";
    } else {
        $cmd = "/usr/bin/grep --line-buffered blacklst /var/log/firewall.log";
    }

    if ($filter ne '') {
        $cmd .= " | grep --line-buffered ".shell_quote($filter);
    }

    if (not($follow)) {
        $cmd .= " | /usr/bin/tail -n ".shell_quote($lines);
    }

    my @procs_to_kill = (
        "timeout .*/var/log/firewall\.log",
        "tail .*/var/log/firewall\.log",
        "grep --line-buffered",
        "journalctl .*/var/log/firewall\.log"
    );

    for (@procs_to_kill) {
        my @pids = `pgrep -f "$_"`;
        chomp @pids;

        foreach my $pid (@pids) {
            if ($pid ne "" && $pid != $$) {
                system("kill -9 $pid");
            }
        }
    }
    system("$watchdog $cmd");
}

if($cmd eq 'follow') {
    dump_logs($lines, 1);
} elsif ($cmd eq 'dump') {
    dump_logs($lines, 0);
} else {
    error();
}
